# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Miranda Svanidze
tagline:          'Leibniz Institute of Agricultural Development in Transition Economies (IAMO)'
description:      'Research Associate | Agricultural Economist'
url:              http://miranidze.github.io
baseurl:          

author:
  name:           'Miranda Svanidze'
  url:            http://miranidze.github.io

paginate:         5
paginate_path: "/page:num/"
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mirandize

plugins:
  - jekyll-paginate
  - jekyll-gist

# Markdown configuration
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true